# Generated by Django 3.1.3 on 2020-11-29 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='authot',
            new_name='author',
        ),
    ]
